### ISSUE TITLE
アクセシビリティチェック ラジオボタン

### ISSUE THREAD

**Issue by tunagohan** [ysk1180/bigtweet2#1]
### 対象

<img width="1440" alt="2018-10-06 14 14 35" src="https://user-images.githubusercontent.com/19791597/46567715-89ca6e80-c972-11e8-973d-a9692a868cd0.png">

### ラジオボタンについて
PCページのみの指摘にはなってしまいますが、
ユーザが選択した左側にラジオボタンの 'checked' が付くのは明確なのですが
横並びの項目が多いと
どっちに選択が向いているのかが分かりにくい場合があります。

そのためラジオボタン自体の存在を隠し選択状態をあわらす枠を付けるように制御するか
横並び項目を減らしてあげる必要があります。

**Comment by ysk1180** [comment]
ラジオボタンはモダンっぽくないので、いい感じに枠で囲ってあげる感じにしたいと思ってました！

**Comment by ysk1180** [comment]
こんな感じになりましたー！

ありがとうございます！！

![2018-10-13 17 05 05](https://user-images.githubusercontent.com/34002043/46903030-29a37180-cf0a-11e8-8f0d-894fd0af14fd.png)
