### ISSUE TITLE
画像量が多いため読み込みに時間がかかる問題

### ISSUE THREAD

**Issue by tunagohan** [ysk1180/bigtweet2#15]
事前にサムネイルを最大圧縮した状態で用意するか
ajaxなどを利用し非同期で取り寄せるなどしないと
スマホなどでは辛い事になります。

**Comment by ysk1180** [comment]
画像が増えるにつれてこれは対策が必要だと思ってました。ありがとうございます！

**Comment by ysk1180** [comment]
62085a520783e4758513c10369ab499c192431ee にて圧縮したサムネイル画像を利用する形に変更しました。

**Comment by ysk1180** [comment]
画像圧縮・遅延読み込みに対応したためCloseします。

**Comment by tunagohan** [comment]
LGTM
