### ISSUE TITLE
メソッドのprivate化

### ISSUE THREAD

**Issue by tunagohan** [ysk1180/bigtweet2#6]
https://github.com/ysk1180/bigtweet2/blob/b15e653eda206719aafd58d2c49ba9c6198dc07a/app/controllers/posts_controller.rb#L28-L55
このあたりのコードを読み解くと他で利用されてはならない
もしくは他で利用しないことから `private` にする方が良いかなーと思いました！

**Comment by ysk1180** [comment]
そうですね！アップロード系の処理はモデルに切り出すのが良さそうです 👍
