### ISSUE TITLE
modelの未定義について

### ISSUE THREAD

**Issue by tunagohan** [ysk1180/bigtweet2#8]
https://github.com/ysk1180/bigtweet2/blob/b15e653eda206719aafd58d2c49ba9c6198dc07a/db/migrate/20180923125748_create_posts.rb#L1-L12

https://github.com/ysk1180/bigtweet2/blob/b15e653eda206719aafd58d2c49ba9c6198dc07a/app/models/post.rb#L1

も、モデルが利用されていない！？
実際中身まで追うことはしていないのですが
使われていない場合migrateが必要なくなるので消してしまっても良いかなと思いました。

**Comment by ysk1180** [comment]
今の所モデル使ってないです笑
投稿データをDBに保存するかどうかは迷いましたが、極力簡単にしようと思ってDBに保存するのはやめています。

今後拡張可能性があるのと、コントローラの処理をモデルに切り出そうと思っているのもあるので、モデルは残しておく方向で考えていますがどうですかね〜:flushed:

**Comment by tunagohan** [comment]
投稿データをDBに保存しておくのは
割とありな選択です！
過去データから画像を持ってきて
再編集という使い方も考えられますし！

その考えの元残すのはありなのでCLOSEいたします！
